# GitHub action based on build-push-action -
# Build testcontainer with cypress and specs
# Push testcontainer to GitHub package  
name: TestcontainerBuildAndPush
on: push
jobs:
  TestcontainerBuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login GitHub packages
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com    
      - name: build and push to GitHub
        uses: docker/build-push-action@v2
        with:
          context: ./cypressd
          file: ./cypressd/Dockerfile
          push: true
          tags: 
            docker.pkg.github.com/sim007/cicdfe/testcontainer:latest