# GitHub action based on https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/nightly.yml 
# Run testcontainer with specs

# GitHub action based on google.nl
# Build test container with cypress with specs
# Push container to GitHub package  
name: Run testcontainer
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login GitHub packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # repository: sim007/cicdfe/testcontainer
      - name: Docker commands  
        run: docker version

      - name: Docker run testconatiner    
        run: docker container run -w /e2e docker.pkg.github.com/sim007/cicdfe/testcontainer   
