# GitHub action based on 
# Run test container with cypress with specs

name: Run testcontainer
on: push
jobs:
  testcontainer:
    runs-on: ubuntu-latest
    username: ${{ github.actor }}
    password: ${{ secrets.GITHUB_TOKEN }}
    registry: docker.pkg.github.com
    container: sim007/cicdfe/testcontainer:latest
    options: -it -w /e2e
          
